Searching
ECE496-663/SH4RE pull request #41
Opened 2023-03-21 04:50 UTC by bbryanb333

2023-03-22 02:08 UTC, bbryanb333 commented
Searching and filtering for price, star rating and category
integrated agolia
main functions added doSearch() in SearchView
added searchListings() in ListingViewModel

2023-03-22 04:02 UTC, WasifButt commented
can you also trigger the search feature on the searchView page, not just home page. 

i.e. when user enters something in search bar and presses enter the searching algo should happen

2023-03-27 21:11 UTC, americobarros requested changes

2023-03-27 21:11 UTC, americobarros commented on SH4RE/SH4RE/CreateListing/CreateListingView.swift
> +                    guard let number = number else{
this seems like maybe could cause a bug, I would change the variable names to not overlap

2023-03-27 21:11 UTC, americobarros commented on SH4RE/SH4RE/Search/SearchView.swift
> +//Testing for before front end date filter was added get rid of once added
did you want to leave this?

2023-03-27 21:11 UTC, americobarros commented on SH4RE/SH4RE/ViewListing/ViewListingView.swift
> +                    Text("/day")
Price must be set now? No more optional? Also could you add a space between / and day `"/ day"`

2023-03-27 21:11 UTC, americobarros commented on SH4RE/SH4RE/ListingViewModel.swift
> +    func searchListings(searchString: String, minCost:String, maxCost:String, category:String, minRating:Double, postalCode:String, rad:Int, startDate: Date, endDate: Date, completion: @escaping (Boo
so searchModel has all these variables as well. I changed it to pass each of the variables individually when seachListings() is called, however, if you want to refactor for searchListings to grab searchModel directly, then you can.

2023-03-27 21:11 UTC, americobarros commented on SH4RE/SH4RE/ListingViewModel.swift
> +                                      if(startDate != Date(timeIntervalSinceReferenceDate: 0)){
I think this will cause issues, becasue if the search query doesn't happen in the exact same tick, the search will make the interval the current time right? Maybe I don't understand how the date thing works

2023-03-27 21:12 UTC, americobarros commented on SH4RE/SH4RE/ListingViewModel.swift
> +    func searchListings(searchString: String, minCost:String, maxCost:String, category:String, minRating:Double, postalCode:String, rad:Int, startDate: Date, endDate: Date, completion: @escaping (Boo
I refactored it, but you can undo the last commit if you don't like

2023-03-29 16:22 UTC, bbryanb333 commented on SH4RE/SH4RE/CreateListing/CreateListingView.swift
> +                    guard let number = number else{
Thats the standard way I've been seeing to write guard statements. I sorta like if number exists

2023-03-29 16:22 UTC, bbryanb333 commented on SH4RE/SH4RE/Search/SearchView.swift
> +//Testing for before front end date filter was added get rid of once added
Ya it will be a reminder to add the calendar dates once they are added to filters

2023-03-29 16:23 UTC, bbryanb333 commented on SH4RE/SH4RE/ListingViewModel.swift
> +    func searchListings(searchString: String, minCost:String, maxCost:String, category:String, minRating:Double, postalCode:String, rad:Int, startDate: Date, endDate: Date, completion: @escaping (Boo
Yeah that's better thank you

2023-03-29 16:26 UTC, bbryanb333 commented on SH4RE/SH4RE/ListingViewModel.swift
> +                                      if(startDate != Date(timeIntervalSinceReferenceDate: 0)){
The Date(timeIntervalSinceReferenceDate: 0) will always be the same since it will be Jan 1st 1970 since it is the defualt reference date. The 0 just means 0 seconds from the reference date. I'm just using it as a empty date since we would never use it in the app

2023-03-29 16:48 UTC, americobarros commented on SH4RE/SH4RE/CreateListing/CreateListingView.swift
> +                    guard let number = number else{
interesting, never seen this b4

2023-03-29 16:49 UTC, americobarros commented on SH4RE/SH4RE/ListingViewModel.swift
> +                                      if(startDate != Date(timeIntervalSinceReferenceDate: 0)){
got it.

2023-03-30 04:06 UTC, merged